# Generated by Django 5.2.3 on 2025-06-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pic/')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('is_top', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=55, verbose_name='Customer Name')),
                ('cus_ph', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('booking_date', models.DateField(verbose_name='Travel Date')),
                ('booked_on', models.DateField(auto_now_add=True, verbose_name='Booked On')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.package')),
            ],
        ),
    ]
