# Generated by Django 5.2.3 on 2025-06-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_package_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cus_ph',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
